export const MAX_LONGITUDINAL_SIMULATION_STEPS = 720;
export const MAX_LONGITUDINAL_STEP_HOURS = 24;
export const MAX_LONGITUDINAL_TOTAL_HOURS =
  MAX_LONGITUDINAL_SIMULATION_STEPS * MAX_LONGITUDINAL_STEP_HOURS;
